spring:
  application:
    name: mongdb-demo
  data:
    mongodb:
      host: 47.97.200.18
      port: 27017
      username: admin
      password: admin
      database: admin
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG

